### ISSUE TITLE
Return Pythonic Types: `get_attribute`

### ISSUE THREAD

**Issue by neetVeritas** [neetVeritas/pyselenium-js#44]
The method `get_attribute` should be modified to return Pythonic types rather than strings.

**Comment by rorosentrater** [comment]
made a method to convert JS types to python types "__type2python"

**Comment by neetVeritas** [comment]
I'll go ahead and wrap the methods above with the newly created function, I'll just need to work in some logical limits for DOM properties.

**Comment by neetVeritas** [comment]
After testing all use cases, the it seems the only method that needs to be patched is `get_attribute`. The methods that return object/dom property values, will always return the explicit type because Selenium will take care of that for us -- it's managed in `execute_script`.

The problem arises when we call `element.getAttribute(args*)` in javascript which will always return a string.

**Comment by neetVeritas** [comment]
Resolved: https://github.com/neetVeritas/pyselenium-js/pull/46
